// Sample train data - in production, this would come from a database
export const trainData = [
  {
    TrainNumber: "12049",
    TrainName: "Gatimaan Express",
    Type: "Superfast",
    Priority: "goods-only",
    Origin: "Agra Cantt",
    Origin_Code: "AGC",
    Destination: "Tundla Junction",
    Destination_Code: "TDL",
    AssignedRoute: "AGC->TDL",
    ScheduledDeparture: "04:59",
    ActualDeparture: "04:59",
    ScheduledArrival: "07:21",
    ActualArrival: "07:21",
    DwellTimeMinutes: "6",
    RunningTimeMinutes: "142",
    PlatformAssigned: "4",
    TrackStatus: "maintenance",
    SignalState: "green",
    Weather: "clear",
    PassengerLoad: "0.83",
    Disruption: "none"
  },
  {
    TrainNumber: "12002",
    TrainName: "Bhopal Shatabdi Express",
    Type: "Express",
    Priority: "normal",
    Origin: "New Delhi",
    Origin_Code: "NDLS",
    Destination: "Mathura Junction",
    Destination_Code: "MKR",
    AssignedRoute: "NDLS->MKR",
    ScheduledDeparture: "05:50",
    ActualDeparture: "05:50",
    ScheduledArrival: "07:37",
    ActualArrival: "07:37",
    DwellTimeMinutes: "8",
    RunningTimeMinutes: "107",
    PlatformAssigned: "1",
    TrackStatus: "free",
    SignalState: "red",
    Weather: "storm",
    PassengerLoad: "0.94",
    Disruption: "weather_delay"
  },
  {
    TrainNumber: "12282",
    TrainName: "Taj Express",
    Type: "Goods",
    Priority: "goods-only",
    Origin: "Agra Cantt",
    Origin_Code: "AGC",
    Destination: "Tundla Junction",
    Destination_Code: "TDL",
    AssignedRoute: "AGC->TDL",
    ScheduledDeparture: "05:08",
    ActualDeparture: "05:08",
    ScheduledArrival: "08:01",
    ActualArrival: "08:01",
    DwellTimeMinutes: "9",
    RunningTimeMinutes: "173",
    PlatformAssigned: "3",
    TrackStatus: "free",
    SignalState: "red",
    Weather: "rain",
    PassengerLoad: "0.95",
    Disruption: "signal_failure"
  },
  {
    TrainNumber: "12628",
    TrainName: "Kerala Express",
    Type: "Superfast",
    Priority: "goods-only",
    Origin: "Agra Cantt",
    Origin_Code: "AGC",
    Destination: "Tundla Junction",
    Destination_Code: "TDL",
    AssignedRoute: "AGC->TDL",
    ScheduledDeparture: "05:01",
    ActualDeparture: "05:06",
    ScheduledArrival: "07:36",
    ActualArrival: "07:41",
    DwellTimeMinutes: "7",
    RunningTimeMinutes: "155",
    PlatformAssigned: "1",
    TrackStatus: "occupied",
    SignalState: "red",
    Weather: "fog",
    PassengerLoad: "0.87",
    Disruption: "none"
  },
  {
    TrainNumber: "12828",
    TrainName: "Chhattisgarh Sampark Kranti",
    Type: "Passenger",
    Priority: "high",
    Origin: "New Delhi",
    Origin_Code: "NDLS",
    Destination: "Mathura Junction",
    Destination_Code: "MKR",
    AssignedRoute: "NDLS->MKR",
    ScheduledDeparture: "04:42",
    ActualDeparture: "04:42",
    ScheduledArrival: "07:38",
    ActualArrival: "07:38",
    DwellTimeMinutes: "2",
    RunningTimeMinutes: "176",
    PlatformAssigned: "2",
    TrackStatus: "occupied",
    SignalState: "yellow",
    Weather: "storm",
    PassengerLoad: "0.65",
    Disruption: "none"
  }
];

export const platformData = [
  {
    Station: "New Delhi",
    Station_Code: "NDLS",
    Platform: "1",
    ConnectedTracks: "2,1,3",
    Platform_Maintenance: "free",
    Track_Status: ""
  },
  {
    Station: "New Delhi",
    Station_Code: "NDLS",
    Platform: "2",
    ConnectedTracks: "2,1,3",
    Platform_Maintenance: "free",
    Track_Status: ""
  },
  {
    Station: "New Delhi",
    Station_Code: "NDLS",
    Platform: "3",
    ConnectedTracks: "3,1",
    Platform_Maintenance: "free",
    Track_Status: ""
  },
  {
    Station: "New Delhi",
    Station_Code: "NDLS",
    Platform: "4",
    ConnectedTracks: "3,2,1",
    Platform_Maintenance: "free",
    Track_Status: ""
  },
  {
    Station: "Agra Cantt",
    Station_Code: "AGC",
    Platform: "1",
    ConnectedTracks: "1,2",
    Platform_Maintenance: "free",
    Track_Status: ""
  }
];
